#  • ▌ ▄ ·. ▄▄▄▄·     ▄▄▄ .·▄▄▄▄  ▪  ▄▄▄▄▄      ▄▄▄       ▄▄▄·▄▄▄       
#  ·██ ▐███▪▐█ ▀█▪    ▀▄.▀·██▪ ██ ██ •██  ▪     ▀▄ █·    ▐█ ▄█▀▄ █·▪    
#  ▐█ ▌▐▌▐█·▐█▀▀█▄    ▐▀▀▪▄▐█· ▐█▌▐█· ▐█.▪ ▄█▀▄ ▐▀▀▄      ██▀·▐▀▀▄  ▄█▀▄
#  ██ ██▌▐█▌██▄▪▐█    ▐█▄▄▌██. ██ ▐█▌ ▐█▌·▐█▌.▐▌▐█•█▌    ▐█▪·•▐█•█▌▐█▌.▐▌
#  ▀▀  █▪▀▀▀·▀▀▀▀      ▀▀▀ ▀▀▀▀▀• ▀▀▀ ▀▀▀  ▀█▄▀▪.▀  ▀    .▀   .▀  ▀ ▀█▄▀▪
#                Magicbane Emulator Project © 2013 - 2022
#                           www.magicbane.com

REGION_CONTENTBEHAVIOR_SHOWNONE = 0
REGION_CONTENTBEHAVIOR_SHOWCHARACTERS = 1
REGION_CONTENTBEHAVIOR_SHOWOBJECTS = 2
REGION_CONTENTBEHAVIOR_SHOWALL = 3

REGION_CONTENTBEHAVIOR_TO_STRING = {
    REGION_CONTENTBEHAVIOR_SHOWNONE: 'SHOWNONE',
    REGION_CONTENTBEHAVIOR_SHOWCHARACTERS: 'SHOWCHARACTERS',
    REGION_CONTENTBEHAVIOR_SHOWOBJECTS: 'SHOWOBJECTS',
    REGION_CONTENTBEHAVIOR_SHOWALL: 'SHOWALL',
}

STRING_TO_REGION_CONTENTBEHAVIOR = {
    'SHOWNONE': REGION_CONTENTBEHAVIOR_SHOWNONE,
    'SHOWCHARACTERS': REGION_CONTENTBEHAVIOR_SHOWCHARACTERS,
    'SHOWOBJECTS': REGION_CONTENTBEHAVIOR_SHOWOBJECTS,
    'SHOWALL': REGION_CONTENTBEHAVIOR_SHOWALL,
}

REGION_STATE_INSIDE = 1
REGION_STATE_OUTSIDE = 2

REGION_STATE_TO_STRING = {
    REGION_STATE_INSIDE: 'INSIDE',
    REGION_STATE_OUTSIDE: 'OUTSIDE',
}

STRING_TO_REGION_STATE = {
    'INSIDE': REGION_STATE_INSIDE,
    'OUTSIDE': REGION_STATE_OUTSIDE,
}

LEVEL_TYPE_EXTERIOR = False
LEVEL_TYPE_INTERIOR = True

LEVEL_TYPE_TO_STRING = {
    LEVEL_TYPE_EXTERIOR: 'EXTERIOR',
    LEVEL_TYPE_INTERIOR: 'INTERIOR',
}

STRING_TO_LEVEL_TYPE = {
    'EXTERIOR': LEVEL_TYPE_EXTERIOR,
    'INTERIOR': LEVEL_TYPE_INTERIOR,
}
