ATTACK_RESIST_UNKNOWN = 0
ATTACK_RESIST_SLASHING = 1
ATTACK_RESIST_CRUSHING = 2
ATTACK_RESIST_PIERCING = 3
ATTACK_RESIST_POISON = 4
ATTACK_RESIST_LIGHTNING = 5
ATTACK_RESIST_MAGIC = 6
ATTACK_RESIST_FIRE = 7
ATTACK_RESIST_COLD = 8
ATTACK_RESIST_MENTAL = 9
ATTACK_RESIST_HOLY = 10
ATTACK_RESIST_SIEGE = 11
ATTACK_RESIST_HEALING = 12
ATTACK_RESIST_BLEEDING = 13
ATTACK_RESIST_UNHOLY = 14
ATTACK_RESIST_ANTISIEGE = 15

ATTACK_RESIST_TO_STRING = {
    ATTACK_RESIST_UNKNOWN: 'UNKNOWN',
    ATTACK_RESIST_SLASHING: 'SLASHING',
    ATTACK_RESIST_CRUSHING: 'CRUSHING',
    ATTACK_RESIST_PIERCING: 'PIERCING',
    ATTACK_RESIST_POISON: 'POISON',
    ATTACK_RESIST_LIGHTNING: 'LIGHTNING',
    ATTACK_RESIST_MAGIC: 'MAGIC',
    ATTACK_RESIST_FIRE: 'FIRE',
    ATTACK_RESIST_COLD: 'COLD',
    ATTACK_RESIST_MENTAL: 'MENTAL',
    ATTACK_RESIST_HOLY: 'HOLY',
    ATTACK_RESIST_SIEGE: 'SIEGE',
    ATTACK_RESIST_HEALING: 'HEALING',
    ATTACK_RESIST_BLEEDING: 'BLEEDING',
    ATTACK_RESIST_UNHOLY: 'UNHOLY',
    ATTACK_RESIST_ANTISIEGE: 'ANTISIEGE',
}

STRING_TO_ATTACK_RESIST = {
    'UNKNOWN': ATTACK_RESIST_UNKNOWN,
    'SLASHING': ATTACK_RESIST_SLASHING,
    'CRUSHING': ATTACK_RESIST_CRUSHING,
    'PIERCING': ATTACK_RESIST_PIERCING,
    'POISON': ATTACK_RESIST_POISON,
    'LIGHTNING': ATTACK_RESIST_LIGHTNING,
    'MAGIC': ATTACK_RESIST_MAGIC,
    'FIRE': ATTACK_RESIST_FIRE,
    'COLD': ATTACK_RESIST_COLD,
    'MENTAL': ATTACK_RESIST_MENTAL,
    'HOLY': ATTACK_RESIST_HOLY,
    'SIEGE': ATTACK_RESIST_SIEGE,
    'HEALING': ATTACK_RESIST_HEALING,
    'BLEEDING': ATTACK_RESIST_BLEEDING,
    'UNHOLY': ATTACK_RESIST_UNHOLY,
    'ANTISIEGE': ATTACK_RESIST_ANTISIEGE,
}
